### ISSUE TITLE
🐛 Charm Issues

### ISSUE THREAD

**Issue by Simseru** [TabulaRasaXI/TabulaRasa#142]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
I am not playing BST but a friend is and I know a lot of people were complaining about it recently so I took a look. I believe there is a small unintentional error causing the issue.

The charisma check portion is written as
`
float chrRatio = ((PCharmer->CHR() - PTarget->CHR())) / 100.f;`
`charmChance *= (1.f * (chrRatio * 5.83));`

I think maybe the below was the intention but the wrong algebraic symbol was used on accident.
`charmChance *= (1.f + (chrRatio * 5.83));`

Using the formula as is right now. 
If you have 10 more CHR than the target it is divided by 100 to .10. (.10 is then * 5.83) to 0.583. Then  1 * .583 == .583. It then multiplies your charm rate based on lvldif and mobdifficulty by .583 which almost cuts it in half, because you had 10 more CHR then the target. 

IE, a 8BST trying to charm a EP lvl 1 that you have 5 more CHR then failing cause base success is something like 80.0(lvl and difficulty math) * .29(chr check math) == 23% chance to charm something lower than you with less chr.

If that part above was additive it would be 1 + .583 = 1.583 and your charm rate would get 58% HIGHER cause you have 10 more CHR then the target instead of LOWER.

Lets also say you have even just 1 less CHR than the target. -1 /100 == -.01. [-.1 * 5.83] == -.0583. [ 1 * -.0583] = -.0583.  You will then multiple your chance to charm by a negative number which will remain a negative number and then floor to 0. 

In theory how it is currently coded if the mob has more CHR than you, even by 1, it will be impossible to charm as the negative number will be clamped up to 0. And if you have more CHR then the target you are losing charm chance for how much more you have until you have at least 18 more CHR than the mob, then the formula starts to break even or add a bonus.

**Comment by MeyiLekoh** [comment]
Charm is ASS right now. Even on Easy Preys I have a high fail rate.

Day 1 - 
EM - 1/24
DC (1 level) - 3/19
DC (2 levels) - 2/12
EP (3 levels) 1/3

7 successes out of 58, about a 12% success. 

Day 2 - 
DC (2 levels) - 1/4
EP (3 levels) - 3/6
EP (4 levels) - 8/29
EP (5 levels) - 9/23
EP (6 levels) - 6/12
EP (7 levels) - 4/12
EP (8 levels) - 2/3

33 successes out of 89, about a 37% success (on easy preys).

This is not era accurate. Era retail I leveled BST to 75 on an Elvaan, and then leveled BST to 75 again on a Taru. 

Additionally I noticed if I failed a charm on one of the monsters, I wasn't able to charm it even after several attempts. Typically you should be able to (eventually) charm a pet that you failed to charm previously. If it's because it's flooring charisma, that would make sense as to what I'm experiencing, but that's not accurate to how charm should function.

As monsters become weaker to you (Decent Challenge, Easy Prey, Too Weak), they should also become easier to charm.

I'd be happy to go pay for a month of retail and prove that charming lower level monsters should be easier than it is.  I doubt the formula has changed much over the years, especially as BSTs have moved on to jugs.

**Comment by twelvedudes** [comment]
It’s very bad so bad I don’t even use it. I just use jugs

**Comment by RunAwayDSP** [comment]
this shouldnt be as bad right now... there are still issues that need to be resolved though
