### ISSUE TITLE
🐛 Elemental Weapon Improper Damage

### ISSUE THREAD

**Issue by MeyiLekoh** [TabulaRasaXI/TabulaRasa#82]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

Elemental weapons are supposed to do shit damage on regular monsters, but decent on physically resistant/magically sensitive monsters, like Elementals.

Fought a Light Elemental in Qufim Island as a level 50 THF/NIN, the elemental conned as level 35 Easy Prey. Gust Slash, Wind Based, did 35 damage. Viper Bite (while currently broken) did 106 Damage.

I don't have a screenshot, but Gust Slash/Cyclone was doing decent damage on Yagudos in Giddeus (Mendicant, Persecutor, Piper, etc; the ones 11-18 by Hoo Mjuu). I think the properties are incorrect for elemental weapon skills. 

## Steps to reproduce

1. Get 100% TP with a weapon that can use elemental weaponskills. (Ex. Dagger + Gust Slash)
2. Use on Elemental not weak to that element. (Ex. Light Elemental + Gust Slash (wind))
3. Compare to Gust Slash used on regular monsters.

## Expected behavior

Doing decent damage on magic sensitive/physically resistant monsters, like Elementals. Doing poop damage on regular monsters.

![Broken Gust Slash](https://user-images.githubusercontent.com/47701928/178128500-31c2804c-fc80-4233-9cc6-3a98d8bde1b0.png)

**Comment by 0phie** [comment]
Inherently magical weaponskills have a very low accuracy compared to magic or physical weaponskills if not combined with copious amounts of INT or their relevant stat. I have tested gust slash extensively and there appears to be no issues with it as it appears to be operating normally. There is a high amount of variance, but that is normal for magical weaponskills due to a steeper penalty on magic accuracy when calculating with a weapon skill rather than magic skill.

**Comment by soapytoast** [comment]
this has since been resolved from our current understanding.
